-- ===========================================================================
-- all.sql  —  full schema in one paste (generated by concatenating the
-- individual files in dependency order). Run this first, then seed.sql.
-- Order: setup -> site_settings -> menu -> specials -> image_overrides -> storage
-- Idempotent: safe to re-run. Regenerate with the repo's concat of these files.
-- ===========================================================================


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> setup.sql <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ===========================================================================
-- setup.sql  —  RUN FIRST.
-- Foundation for auth/RBAC + audit trail. Everything else depends on the
-- touch_updated_at() / is_admin() helpers created here.
-- Idempotent: safe to re-run.
-- ===========================================================================

-- Keep updated_at fresh on every UPDATE. Reused by every table's touch trigger.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- user_profiles — admin/employee role + per-section permission keys.
-- ---------------------------------------------------------------------------
create table if not exists public.user_profiles (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  role        text not null check (role in ('admin', 'employee')),
  permissions text[] not null default '{}',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- security definer so RLS policies on user_profiles can check admin status
-- WITHOUT recursing into user_profiles' own policies.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.user_profiles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

alter table public.user_profiles enable row level security;

drop policy if exists user_profiles_self_select on public.user_profiles;
create policy user_profiles_self_select on public.user_profiles
  for select using (user_id = auth.uid());

drop policy if exists user_profiles_admin_all on public.user_profiles;
create policy user_profiles_admin_all on public.user_profiles
  for all using (public.is_admin()) with check (public.is_admin());

drop trigger if exists user_profiles_touch on public.user_profiles;
create trigger user_profiles_touch before update on public.user_profiles
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- activity_logs — append-only audit trail. Written by the service role only.
-- ---------------------------------------------------------------------------
create table if not exists public.activity_logs (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid references auth.users(id) on delete set null,
  user_email text,
  action     text not null check (action in ('create','update','delete','login','logout')),
  table_name text not null,
  record_id  text,
  details    text,
  created_at timestamptz not null default now()
);

alter table public.activity_logs enable row level security;

-- Admins can read the log.
drop policy if exists activity_logs_admin_select on public.activity_logs;
create policy activity_logs_admin_select on public.activity_logs
  for select using (public.is_admin());

-- Minimal mode (publishable key only): logs are written by the logged-in staff
-- user via the anon client, so authenticated users may INSERT. (If you later add
-- a service-role/secret key, drop this policy and write logs server-side for a
-- tamper-proof trail.)
drop policy if exists activity_logs_authed_insert on public.activity_logs;
create policy activity_logs_authed_insert on public.activity_logs
  for insert with check (auth.uid() is not null);

create index if not exists activity_logs_created_at_idx
  on public.activity_logs (created_at desc);

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> site_settings.sql <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ===========================================================================
-- site_settings.sql  —  singleton (id = 1) JSON override over code defaults.
-- The real defaults live in lib/settings.ts (SETTINGS_DEFAULTS); this row only
-- stores a partial override that getSettings() deep-merges over them. If the
-- row is missing/empty the site renders 100% from code. Requires setup.sql.
-- ===========================================================================

create table if not exists public.site_settings (
  id         int primary key default 1 check (id = 1),
  data       jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.site_settings enable row level security;

-- Everyone can read settings (they drive the public header/footer/JSON-LD).
drop policy if exists site_settings_public_select on public.site_settings;
create policy site_settings_public_select on public.site_settings
  for select using (true);

-- Any authenticated (admin) user can write.
drop policy if exists site_settings_admin_write on public.site_settings;
create policy site_settings_admin_write on public.site_settings
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

drop trigger if exists site_settings_touch on public.site_settings;
create trigger site_settings_touch before update on public.site_settings
  for each row execute function public.touch_updated_at();

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> menu.sql <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ===========================================================================
-- menu.sql  —  two collections: menu_categories + menu_items.
-- Public reads published rows; any authed user has full access. Requires
-- setup.sql. Follows the standard RLS pattern (CMS-GUIDE §4.2).
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- menu_categories
--   column_group (1-3) preserves the public menu page's 3-column layout.
-- ---------------------------------------------------------------------------
create table if not exists public.menu_categories (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  slug          text not null unique,
  column_group  int not null default 1 check (column_group between 1 and 3),
  display_order int not null default 0,
  is_published  boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

alter table public.menu_categories enable row level security;

drop policy if exists menu_categories_public_select on public.menu_categories;
create policy menu_categories_public_select on public.menu_categories
  for select using (is_published = true);

drop policy if exists menu_categories_admin_select on public.menu_categories;
create policy menu_categories_admin_select on public.menu_categories
  for select using (auth.uid() is not null);
drop policy if exists menu_categories_admin_insert on public.menu_categories;
create policy menu_categories_admin_insert on public.menu_categories
  for insert with check (auth.uid() is not null);
drop policy if exists menu_categories_admin_update on public.menu_categories;
create policy menu_categories_admin_update on public.menu_categories
  for update using (auth.uid() is not null);
drop policy if exists menu_categories_admin_delete on public.menu_categories;
create policy menu_categories_admin_delete on public.menu_categories
  for delete using (auth.uid() is not null);

drop trigger if exists menu_categories_touch on public.menu_categories;
create trigger menu_categories_touch before update on public.menu_categories
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- menu_items
--   price is TEXT on purpose — prices carry the "$" and are edited verbatim.
--   is_highlight + highlight_group + highlight_order drive the home page's
--   curated "Menu highlights" section (groups don't map 1:1 to categories).
-- ---------------------------------------------------------------------------
create table if not exists public.menu_items (
  id              uuid primary key default gen_random_uuid(),
  category_id     uuid not null references public.menu_categories(id) on delete cascade,
  name            text not null,
  price           text,
  description     text,
  sub             text,
  tags            text[] not null default '{}',
  is_highlight    boolean not null default false,
  highlight_group text,
  highlight_order int not null default 0,
  display_order   int not null default 0,
  is_published    boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists menu_items_category_idx
  on public.menu_items (category_id);
create index if not exists menu_items_highlight_idx
  on public.menu_items (is_highlight) where is_highlight = true;

alter table public.menu_items enable row level security;

drop policy if exists menu_items_public_select on public.menu_items;
create policy menu_items_public_select on public.menu_items
  for select using (is_published = true);

drop policy if exists menu_items_admin_select on public.menu_items;
create policy menu_items_admin_select on public.menu_items
  for select using (auth.uid() is not null);
drop policy if exists menu_items_admin_insert on public.menu_items;
create policy menu_items_admin_insert on public.menu_items
  for insert with check (auth.uid() is not null);
drop policy if exists menu_items_admin_update on public.menu_items;
create policy menu_items_admin_update on public.menu_items
  for update using (auth.uid() is not null);
drop policy if exists menu_items_admin_delete on public.menu_items;
create policy menu_items_admin_delete on public.menu_items
  for delete using (auth.uid() is not null);

drop trigger if exists menu_items_touch on public.menu_items;
create trigger menu_items_touch before update on public.menu_items
  for each row execute function public.touch_updated_at();

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> specials.sql <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ===========================================================================
-- specials.sql  —  "What's on" / specials cards collection.
-- Public reads published rows; any authed user has full access. Requires
-- setup.sql. Seeded empty — the home "What's on" section falls back to code
-- defaults until an admin publishes rows.
-- ===========================================================================

create table if not exists public.specials (
  id            uuid primary key default gen_random_uuid(),
  title         text not null,
  body          text,
  image_url     text,
  starts_at     timestamptz,
  ends_at       timestamptz,
  display_order int not null default 0,
  is_published  boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

alter table public.specials enable row level security;

drop policy if exists specials_public_select on public.specials;
create policy specials_public_select on public.specials
  for select using (is_published = true);

drop policy if exists specials_admin_select on public.specials;
create policy specials_admin_select on public.specials
  for select using (auth.uid() is not null);
drop policy if exists specials_admin_insert on public.specials;
create policy specials_admin_insert on public.specials
  for insert with check (auth.uid() is not null);
drop policy if exists specials_admin_update on public.specials;
create policy specials_admin_update on public.specials
  for update using (auth.uid() is not null);
drop policy if exists specials_admin_delete on public.specials;
create policy specials_admin_delete on public.specials
  for delete using (auth.uid() is not null);

drop trigger if exists specials_touch on public.specials;
create trigger specials_touch before update on public.specials
  for each row execute function public.touch_updated_at();

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> image_overrides.sql <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ===========================================================================
-- image_overrides.sql  —  photo-swap slot table (override over code defaults).
-- Keyed by a stable slot id (e.g. "home.hero", "gallery.mural"). A row means
-- "use this url instead of the hardcoded /uploads default". No row = the code
-- default renders. Public read (overrides show on the live site); authed write.
-- Requires setup.sql. Seeded empty.
-- ===========================================================================

create table if not exists public.image_overrides (
  slot       text primary key,
  url        text not null,
  updated_at timestamptz not null default now()
);

alter table public.image_overrides enable row level security;

drop policy if exists image_overrides_public_select on public.image_overrides;
create policy image_overrides_public_select on public.image_overrides
  for select using (true);

drop policy if exists image_overrides_admin_write on public.image_overrides;
create policy image_overrides_admin_write on public.image_overrides
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

drop trigger if exists image_overrides_touch on public.image_overrides;
create trigger image_overrides_touch before update on public.image_overrides
  for each row execute function public.touch_updated_at();

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> storage.sql <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ===========================================================================
-- storage.sql  —  public "media" bucket for admin image uploads.
-- Public read; authenticated insert/update/delete. Uploads happen client-side
-- from the admin (ImageUploader), which stores the returned public URL in the
-- relevant row/field (e.g. image_overrides.url, specials.image_url).
-- Safe to re-run.
-- ===========================================================================

insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

drop policy if exists media_public_read on storage.objects;
create policy media_public_read on storage.objects
  for select using (bucket_id = 'media');

drop policy if exists media_authed_insert on storage.objects;
create policy media_authed_insert on storage.objects
  for insert with check (bucket_id = 'media' and auth.uid() is not null);

drop policy if exists media_authed_update on storage.objects;
create policy media_authed_update on storage.objects
  for update using (bucket_id = 'media' and auth.uid() is not null);

drop policy if exists media_authed_delete on storage.objects;
create policy media_authed_delete on storage.objects
  for delete using (bucket_id = 'media' and auth.uid() is not null);
